services:
  portainer:
    image: portainer/portainer-ce:2.21.4
    ports:
    # TCP tunnel server over port 8000 [...] only required if you plan to use the Edge compute features with Edge agents.
    # - "8000:8000"  # 
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "cops_portainer_data:/data"
volumes:
  cops_portainer_data:
    driver: local
