on:
  push:
    branches-ignore:
    - main

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - name: pull-request
      run: gh pr create --title "My pull request" --body "Description" || gh pr edit --title "My pull request" --body "Description"
